server:
  port: 8080

logging:
  config: classpath:logback.xml

spring:
  http:
    converters:
      preferred-json-mapper: fastjson
  devtools:
      restart:
        enabled: true
  profiles:
      active: dev
  datasource:
    name: scfl
    url: jdbc:mysql://127.0.0.1:3306/dispatching_center?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20




